version: '3.1'
services:
    web-api:
        image: rafaelsantos/poweplants-api:latest
        container_name: poweplants-api
        build:
            context: ../src
            dockerfile: ./PowerPlants.Api/Dockerfile
        ports:
            - "8888:8888"            
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:8888